name: sca_fuel
description: نظام SCA Fuel لمتابعة استهلاك الوقود لأسطول هيئة قناة السويس
publish_to: none
version: 1.3.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  supabase_flutter: ^2.8.0
  provider: ^6.0.5
  flutter_secure_storage: ^8.0.0
  shared_preferences: ^2.1.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  file_picker: ^10.3.2
  excel: ^2.0.0
  pdf: ^3.12.0
  desktop_drop: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/bus.jpg
    - assets/sca.png
    - assets/logo.png
    - assets/fonts/arial.ttf
